### ISSUE TITLE
[Feature Request] Read me + Tutorial

### ISSUE THREAD

**Issue by coeurGG** [Speyedr/socialclub-notification-blocker#8]
Adding a read me for people who're not that good with computer things, and translation of this. (I can help for the French traduction).

I can even do a video for the read me if needed. 

LMK if interested, I can give you my discord!

**Comment by Speyedr** [comment]
Sure, this could work. I was initially considering creating a tutorial video on how to acquire and use the program but I didn't know if it would've been worth it because at the time the project was only getting like, 30 views a day.

Community translation is always good. You could upload a translated version of the README.md file here and I can add it to the project, or you can fork the project and add the translation to your own version and I'll pull your translation from your fork instead. However, keeping the file up-to-date with changes in case I need to add or remove stuff from the README.md could be a bit of a hassle.

**Comment by coeurGG** [comment]
I will upload a translation for the readme here. About the tutorial, it's still worth it, your software will be well known by the end of the week already

**Comment by coeurGG** [comment]
USAGE

1. Télécharger et extraire (vous pouvez le build vous-même). Le lien direct pour télécharger la dernière version du logiciel est au-dessus de ce message.

2. Lancez 'SCBlocker.exe' en tant qu'administrateur.

	* Autrement, si vous avez Python installé, vous pouvez directement le lancer via l'interprète (cmd) en exécutant python main.py dans une invite de commande. (Qui nécessite plus de privilèges dans le dossier du repo)
	* Si vous utilisez cette méthode, aucun build n'est nécessaire.

3. Si le programme est en cours d'exécution, et le filtre est sur 'ON', les notifications devraient-être bloquées et ne vont pas atteindre votre client.

4. Utilisez les touches de votre clavier pour naviguer dans le menu.

CONFIGURATION

* Sauvegarde automatique de vos paramètres dans le fichier 'settings.ini'. Ne le touchez pas. Si vous le faîtes, et que le programme crash, supprimez le fichier, et relancez le programme, celui-ci va directement remettre vos paramètres par défaut.
* Si 'LOG BLICKED ACTIVITY' est 'ON4, le programme va "log" (enregistrer) les informations à propos des paquets perdus dans 'debug.log'. Si vous voulez regarder les logs en temps réel, vous pouvez utiliser un logiciel comme mTail.

NOTICES

* Ce programme ne modifie pas l'overlay SocialClub, ou n'importe quel jeu utilisant l'overlay SocialClub lorsqu'il est en cours d'exécution. En théorie, cela signifie que le programme ne viole pas les conditions d'utilisation de Rockstar.
* Ce programme ne contient aucun code qui a nécessité ou utilisé le "reverse-engineering", ou code qui pourrait violer le Copyright de Take-Two interactive.
* Créer ce programme n'a pas requiet la moindre décompilation ou le moindre décryptage du moindre programme ou service fourni ou relié à Rockstar Games / Take-Two Interactive.

FILTRES

* Cette application fournit trois différents filtres heuristiques qui ciblent les différents points dans la chaine de communication entre votre client et l'overlay SocialClub.
* Filtre #1 'DROP_INC_80' est le plus rapide et impacte les performances le moins, mais vous risquez d'être inondés de notifications lorsque le filtre n'est pas activé.
* Filtre #2 'DROP_CLIENT_POST' est activé par défaut, et c'est, probablement ce que la plupart des utilisateurs recherchent.
* Filtre #3 'DROP_LENGTHS' est le plus compliqué, et encore en développement, pour le moment, il n'est pas recommandé.

BUGS / PROBLEMES

* Si vous rencontrez un crash, ou alors un bug qui casse l'application, merci de suivre les instructions et de soumettre votre problème ici.

INSTRUCTIONS POUR LE BUILD

NOTE : Si vous êtes en train de chercher le téléchargement, sans vous-même faire le build, vous devez aller dans Realeases à la place. Ou juste cliquer sur "Download" au haut de cette page.

Windows

1. Installez Python 3 (3.8+ est recommandé)
	* Si c'est votre première installation python, activez la case "Add Python to PATH" rendra la prochaine étape plus facile.

2. Exécutez la commande suivante dans une invite de commande ;

{
:: Make sure to open the command prompt in / navigate to your local repo directory before running these commands.
C:\Users\Speyedr\socialclub-notification-blocker> pip install -r requirements.txt
:: If 'pip' is not recognised (i.e. it wasn't added to PATH) then you will need to provide the absolute path to pip.exe, e.g.
:: Make sure to check your exact install directory (your version number or bundle may be different)
:: C:\Users\Speyedr\socialclub-notification-blocker> "C:\Program Files\Python 3.8\Scripts\pip.exe" install -r requirements.txt
C:\Users\Speyedr\socialclub-notification-blocker> python setup.py build
:: Again, if python is not recognised then you will need to use the absolute path instead:
:: C:\Users\Speyedr\socialclub-notification-blocker> "C:\Program Files\Python 3.8\python.exe" setup.py build
}

CREDITS

Cochons d'Inde

* Wes0617
* MrAlvie

Traduction / Translation

* coeurGG (Traduction Française / French Translation) | Note de Coeur : Si vous trouvez la moindre faute ou une mauvaise traduction, n'hésitez pas à me contacter sur le fork que j'ai fait.

DONATE

PayPal / Card: ko-fi.com/Speyedr
BTC: '347M8sHnahA98c7MjHGmvsb5pVUJeUcMZ5'
ETH: '0xDBAa338137Fc53BA007D7Cf99DD94908e8Fdb6d8'
ADA: 'addr1qy6xlrpv43xjwhjpdvalccjxm3tf46f5cu7uh5uhexzgwyudcmm3ty8entef6tu3dgf8chn70tc3uql0kkrj0f62mw9sxh29w3'

LICENCE

* L'utilisation de ce programme est offert sous la Licence GNU GPLv3.0

CONTRIBUTIONS 

* Si vous avez trouvé un bug, vous pouvez aider en signalant un problème.
* Les demandes d'extraction sont actuellement fermées.
* Selon les termes de la licence de ce projet, vous êtes plus que bienvenu pour créer vos propres variations basées sur mon travail tant que vous conservez tous les avis de droit d'auteur, références, crédits et utilisez également la licence de ce logiciel lors de la publication de tout travail dérivé.


I added a credit about the translation, and I said if there is any translation problem, they can lmk in my Fork.

**Comment by coeurGG** [comment]
Oh.. github added something weird here 
![image](https://user-images.githubusercontent.com/63458253/157217732-b55ac646-1ded-4982-8e4e-0fce2571899a.png)

**Comment by coeurGG** [comment]
I will keep it updated whenever you need. Feel free to add me on a social to work together if you want!

**Comment by Speyedr** [comment]
Sure, I'll get this updated soon. Apparently R* have finally attempted an update to fix the issue, we'll see how long it lasts. I'll keep developing the project as I think there still is a need for some people (such as streamers) to have a way to block invites entirely. Apparently it also blocks phone invites so I think some people might enjoy the quiet there as well.

**Comment by Speyedr** [comment]
> Oh.. github added something weird here ![image](https://user-images.githubusercontent.com/63458253/157217732-b55ac646-1ded-4982-8e4e-0fce2571899a.png)

Ah, that's because GitHub interprets those as referencing issues, discussions or posts. There's ways around that by putting invisible characters been the pound and the number like this: #&nbsp;1

**Comment by Speyedr** [comment]
Community tutorials have popped up around the place which I reckon are more trustworthy than me directly promoting it myself:
https://www.youtube.com/watch?v=bMdLs07SHXU
https://www.youtube.com/watch?v=3tP2mHxjjyU
https://www.youtube.com/watch?v=k2N35VlQfX8

That being said, in the future I'll see about making official release videos / tutorials when changes or updates are made to the program.
