### ISSUE TITLE
cant open it as an administrator

### ISSUE THREAD

**Issue by shackman42** [Speyedr/socialclub-notification-blocker#9]
**Description**

**How to reproduce**

**Screenshots / Debug.log messages**
Pasting messages from your `debug.log` file can help provide important context for the crash.

**System Information**
 - Operating System: [Windows 8.1, Windows 10, Windows 11]
 - Program Version: [v0.1]

**Additional context**

**Comment by Speyedr** [comment]
I'm sorry, but I can't address this issue as you have not provided enough information about how or why the program cannot be opened as Administrator. I don't know if this is an issue with your Windows account's user permissions or perhaps an anti-virus getting in the way or something else.

That being said, I believe a newer version of the builder I'm using supports automatically setting the program to run as Administrator so I should probably look into that.
